language: node_js
install:
  - npm ci
jobs:
  include:
    - stage: test
      script:
        - echo "Running unit tests"
        - npm test
    - stage: lint
      script:
        - npm run lint
    - stage: release
      script:
        - echo "Releasing version"
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        skip_cleanup: true
        on:
          branch: master
