language: node_js
install:
  - npm ci
jobs:
  include:
    - stage: test
      script:
        - echo "Running unit tests"
        - npm test
    - stage: release
      script:
        - echo "Releasing version"
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_API_KEY'
        skip_cleanup: true
